16 stub CREATEUPDOWNCONTROL
44 stub IMAGELIST_SETBKCOLOR
339 stub DPA_SEARCH
332 stub DPA_GETPTR
336 stub DPA_DELETEPTR
329 stub DPA_DESTROY
334 stub DPA_INSERTPTR
13 stub MAKEDRAGLIST
15 stub DRAWINSERT
335 stub DPA_SETPTR
20 pascal -ret16 CreateToolbarEx(word long word word word word ptr word word word word word word) CreateToolbarEx16
328 stub DPA_CREATE
4 pascal -ret16 GetEffectiveClientRect(word ptr ptr) GetEffectiveClientRect16
45 stub IMAGELIST_GETBKCOLOR
42 stub IMAGELIST_GETIMAGECOUNT
333 stub DPA_GETPTRINDEX
40 stub IMAGELIST_CREATE
2 stub MENUHELP
49 stub IMAGELIST_DRAW
43 stub IMAGELIST_SETOVERLAYIMAGE
160 stub CREATEPROPERTYSHEETPAGE
5 stub DRAWSTATUSTEXT
338 stub DPA_SORT
8 stub CREATEMAPPEDBITMAP
3 stub SHOWHIDEMENUCTL
161 stub DESTROYPROPERTYSHEETPAGE
41 stub IMAGELIST_DESTROY
17 pascal -ret16 InitCommonControls() InitCommonControls16
14 stub LBITEMFROMPT
6 pascal -ret16 CreateStatusWindow(long str word word) CreateStatusWindow16
159 stub PROPERTYSHEET
7 stub CREATETOOLBAR
331 stub DPA_CLONE
54 stub IMAGELIST_REPLACEICON
337 stub DPA_DELETEALLPTRS
330 stub DPA_GROW
46 stub IMAGELIST_ADD
53 stub IMAGELIST_ADDICON
